application:
  port: 8080

mongodb:
  username: "user"
  password: "1234"
  #開發使用
  #address: "localhost"
  #部署使用
  address: "mongodb"
  port: 27017

line:
  channel-secret: ""
  channel-access-token: ""
 